GET http://localhost:4000/api/posts/feed/60a7c9347321f91fc52403de
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwYTdjOTM0NzMyMWY5MWZjNTI0MDNkZSIsImlhdCI6MTYyMjU1MDY5Mn0.AzHVmVK6yVBws5oPF_gskTLiMiufkManeITVGQ8TmIs
//eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwYTdjOTM0NzMyMWY5MWZjNTI0MDNkZSIsImlhdCI6MTYyMjU1MDY5Mn0.AzHVmVK6yVBws5oPF_gskTLiMiufkManeITVGQ8TmIs
//60a7c9347321f91fc52403de
//609d2649e58a332092710f45